Sub revez4bombas(area, clp, x, pg)
    
    Dim objSelection10 As AcadSelectionSet
    Dim objBRef1 As AcadBlockReference
    Dim objBRef2 As AcadBlockReference
    Dim varInsertionPoint(2) As Double
    Dim linePointSTR(2) As Double
    Dim linePointEND(2) As Double
    Dim objInsertionPoint(2) As Double
    Dim varAttribs1 As Variant
    
    On Error Resume Next
    Err.Clear
    Set excelApp = GetObject("D:\Teste.xlsx", "Excel.Application")
    excelApp.Visible = True
    Set shtObj = excelApp.Worksheets(1)
    Set shtObj2 = excelApp.Worksheets(2)
    Set shtObj3 = excelApp.Worksheets(3)
    
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
    
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DL" Then
            If varAttribs1(3).TextString = CStr(pg) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - REVEZAMENTO DE BOMBAS"
                addpg = 1
            End If
        End If
    Next objBRef1
    
    If addpg = 0 Then
        addpage objSelection10, area, clp, "DL", pg
    End If
        
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DL" Then
            If varAttribs1(3).TextString = CStr(pg) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - REVEZAMENTO DE BOMBAS"
                addpg = 0
            End If
        End If
    Next objBRef1
       
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "REVEZAMENTO_4BOMBAS_R00", 1, 1, 1, 0)
    ExpBlock objBRef1
    
    objInsertionPoint(0) = varInsertionPoint(0) + 43.9929
    objInsertionPoint(1) = varInsertionPoint(1) - 26.5895
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "PARTIDA DE GRUPO HABILITADA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 12
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "INICIA COMO PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 17.4278
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value) + ", " + UCase(shtObj3.Cells(19, x).Value) + " E " + UCase(shtObj3.Cells(25, x).Value) + " EM FALHA"
    varAttribs1(1).TextString = UCase(shtObj3.Cells(31, x).Value) + " = PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 9.1899
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "CONDIÇÃO DE TROCA OK"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 9.8661
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "LIGADO = 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 10.4729
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "OK PARA OPERAÇÃO = 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 12.6665
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 10.4729
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 10.4729
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 75.9287
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "LIGA COMPLEMENTAR 2"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 12
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "SOMENTE DUAS BOMBAS OK"
    varAttribs1(1).TextString = "(" + UCase(shtObj3.Cells(31, x).Value) + " = COMPLEMENTAR 2)"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 16.1332
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "SOMENTE UMA BOMBA OK"
    varAttribs1(1).TextString = "(" + UCase(shtObj3.Cells(31, x).Value) + " = COMPLEMENTAR 1)"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 12
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "LIGA COMPLEMENTAR 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 10.3879
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "LIGA RESERVA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 332.6226
    objInsertionPoint(1) = objInsertionPoint(1) + 62.1776
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "RESET TEMPO DE EXISTÊNCIA"
    varAttribs1(2).TextString = CStr(pg) + "B"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 1.0111
    objInsertionPoint(1) = objInsertionPoint(1) + 77.9488
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "PRINCIPAL"
    varAttribs1(2).TextString = CStr(pg) + "A"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 28.2617
    objInsertionPoint(1) = objInsertionPoint(1) + 12.5419
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "ESTADO_II", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "E" + area + clp + UCase(shtObj3.Cells(7, x + 3).Value) + "B04PRN"
    varAttribs1(1).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(2).TextString = "PRINCIPAL"
    varAttribs1(3).TextString = "%MW54:X7"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 28.3038
    objInsertionPoint(1) = objInsertionPoint(1) + 12.6303
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "LIGA BOMBA COMP. 1 PARA TROCA"
    varAttribs1(2).TextString = CStr(pg) + "C"
    
    pg = pg + 1
    
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DL" Then
            If varAttribs1(3).TextString = CStr(pg) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - REVEZAMENTO DE BOMBAS"
                addpg = 1
            End If
        End If
    Next objBRef1
       
    If addpg = 0 Then
        addpage objSelection10, area, clp, "DL", pg
    End If
        
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DL" Then
            If varAttribs1(3).TextString = CStr(pg) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - REVEZAMENTO DE BOMBAS"
                addpg = 0
            End If
        End If
    Next objBRef1
        
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "REVEZAMENTO_4BOMBAS2_R00", 1, 1, 1, 0)
    ExpBlock objBRef1
    
    objInsertionPoint(0) = varInsertionPoint(0) + 41.6975
    objInsertionPoint(1) = varInsertionPoint(1) - 18.9331
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "OK PARA OPERAÇÃO = 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 12
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "OK PARA OPERAÇÃO = 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 20.9959
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "OK PARA OPERAÇÃO = 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 92.2206
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "OK PARA OPERAÇÃO = 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 59.5805
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 12
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "SEL. COMO PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 16.9323
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "SEL. COMO PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 16.9323
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "SEL. COMO PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 292.0143
    objInsertionPoint(1) = objInsertionPoint(1) + 13.447
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "ESTADO_II", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "E" + area + clp + UCase(shtObj3.Cells(7, x + 3).Value) + "B03PRN"
    varAttribs1(1).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(2).TextString = "PRINCIPAL"
    varAttribs1(3).TextString = "%MW54:X7"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 0.0218
    objInsertionPoint(1) = objInsertionPoint(1) + 17.8613
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "ESTADO_II", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "E" + area + clp + UCase(shtObj3.Cells(7, x + 3).Value) + "B02PRN"
    varAttribs1(1).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(2).TextString = "PRINCIPAL"
    varAttribs1(3).TextString = "%MW54:X7"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) + 16.9396
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "ESTADO_II", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "E" + area + clp + UCase(shtObj3.Cells(7, x + 3).Value) + "B01PRN"
    varAttribs1(1).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(2).TextString = "PRINCIPAL"
    varAttribs1(3).TextString = "%MW54:X7"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 42.7145
    objInsertionPoint(1) = objInsertionPoint(1) - 42.2406
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "PRINCIPAL"
    varAttribs1(2).TextString = CStr(pg) + "F"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) + 16.9396
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "PRINCIPAL"
    varAttribs1(2).TextString = CStr(pg) + "E"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) + 16.9396
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "PRINCIPAL"
    varAttribs1(2).TextString = CStr(pg) + "D"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 0.2668
    objInsertionPoint(1) = objInsertionPoint(1) + 23.3911
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "TODAS AS BOMBAS OK"
    varAttribs1(2).TextString = CStr(pg) + "I"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) + 20.5825
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "PELO MENOS TRÊS BOMBAS OK"
    varAttribs1(2).TextString = CStr(pg) + "H"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 0.1123
    objInsertionPoint(1) = objInsertionPoint(1) + 33.6069
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "PELO MENOS DUAS BOMBAS OK"
    varAttribs1(2).TextString = CStr(pg) + "G"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) + 22.6426
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "SOMENTE DUAS BOMBAS OK"
    varAttribs1(1).TextString = "(" + UCase(shtObj3.Cells(31, x).Value) + " = COMPLEMENTAR 2)"
    varAttribs1(2).TextString = CStr(pg) + "C"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 59.3621
    objInsertionPoint(1) = objInsertionPoint(1) + 11.5259
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "ESTADO_II", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "E" + area + clp + UCase(shtObj3.Cells(7, x + 3).Value) + "B04CMP2"
    varAttribs1(1).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(2).TextString = "COMPLEMENTAR 2"
    varAttribs1(3).TextString = "%MW54:X1"
            
    objInsertionPoint(0) = objInsertionPoint(0) + 58.7622
    objInsertionPoint(1) = objInsertionPoint(1) + 7.5151
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value) + ", " + UCase(shtObj3.Cells(19, x).Value) + " E " + UCase(shtObj3.Cells(25, x).Value) + " EM FALHA"
    varAttribs1(1).TextString = UCase(shtObj3.Cells(31, x).Value) + " = PRINCIPAL"
    varAttribs1(2).TextString = CStr(pg) + "B"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 0.2007
    objInsertionPoint(1) = objInsertionPoint(1) + 38.722
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "SOMENTE UMA BOMBA OK"
    varAttribs1(1).TextString = "(" + UCase(shtObj3.Cells(31, x).Value) + " = COMPLEMENTAR 1)"
    varAttribs1(2).TextString = CStr(pg) + "A"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 42.5419
    objInsertionPoint(1) = objInsertionPoint(1) + 11.5276
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "ESTADO_II", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "E" + area + clp + UCase(shtObj3.Cells(7, x + 3).Value) + "B04CMP1"
    varAttribs1(1).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(2).TextString = "COMPLEMENTAR 1"
    varAttribs1(3).TextString = "%MW54:X1"
    
    pg = pg + 1
    
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DL" Then
            If varAttribs1(3).TextString = CStr(pg) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - REVEZAMENTO DE BOMBAS"
                addpg = 1
            End If
        End If
    Next objBRef1
     
    If addpg = 0 Then
        addpage objSelection10, area, clp, "DL", pg
    End If
        
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DL" Then
            If varAttribs1(3).TextString = CStr(pg) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - REVEZAMENTO DE BOMBAS"
                addpg = 0
            End If
        End If
    Next objBRef1
        
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "REVEZAMENTO_4BOMBAS3_R00", 1, 1, 1, 0)
    ExpBlock objBRef1
    
    objInsertionPoint(0) = varInsertionPoint(0) + 46.5503
    objInsertionPoint(1) = varInsertionPoint(1) - 23.2997
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "LIGADO = 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.5983
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "LIGADO = 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.5983
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "LIGADO = 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 12.686
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "LIGADO = 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 334.6239
    objInsertionPoint(1) = objInsertionPoint(1) - 153.8547
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "CONDIÇÃO DE TROCA OK"
    varAttribs1(2).TextString = CStr(pg) + "F"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) + 30.6742
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "TODAS AS BOMBAS"
    varAttribs1(1).TextString = "DESLIGADAS"
    varAttribs1(2).TextString = CStr(pg) + "E"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) + 40.6976
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value) + ", " + UCase(shtObj3.Cells(25, x).Value) + " E " + UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "LIGADAS"
    varAttribs1(2).TextString = CStr(pg) + "D"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) + 34.8985
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value) + ", " + UCase(shtObj3.Cells(25, x).Value) + " E " + UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "LIGADAS"
    varAttribs1(2).TextString = CStr(pg) + "C"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) + 35.8826
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value) + ", " + UCase(shtObj3.Cells(19, x).Value) + " E " + UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "LIGADAS"
    varAttribs1(2).TextString = CStr(pg) + "B"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) + 35.9862
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value) + ", " + UCase(shtObj3.Cells(19, x).Value) + " E " + UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "LIGADAS"
    varAttribs1(2).TextString = CStr(pg) + "A"
    
    pg = pg + 1
    
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DL" Then
            If varAttribs1(3).TextString = CStr(pg) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - REVEZAMENTO DE BOMBAS"
                addpg = 1
            End If
        End If
    Next objBRef1
        
    If addpg = 0 Then
        addpage objSelection10, area, clp, "DL", pg
    End If
        
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DL" Then
            If varAttribs1(3).TextString = CStr(pg) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - REVEZAMENTO DE BOMBAS"
                addpg = 0
            End If
        End If
    Next objBRef1
    
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "REVEZAMENTO_4BOMBAS4_R00", 1, 1, 1, 0)
    ExpBlock objBRef1
    
    objInsertionPoint(0) = varInsertionPoint(0) + 47.0036
    objInsertionPoint(1) = varInsertionPoint(1) - 17.8777
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "LIGA BOMBA COMP. 1 PARA TROCA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 9.8928
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "PRINC. FREQUÊNCIA MÁXIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.0443
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "PRINC. FREQUÊNCIA MÁXIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.0443
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "PRINC. FREQUÊNCIA MÁXIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.0443
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "PRINC. FREQUÊNCIA MÁXIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 85.975
    objInsertionPoint(1) = objInsertionPoint(1) - 9.1278
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "PV > SP"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 8.4165
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "PV > SP"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 8.7507
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "PV > SP"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 8.5196
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "PV > SP"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 85.975
    objInsertionPoint(1) = objInsertionPoint(1) - 0.9937
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "COMPL. 1 FREQUÊNCIA MÍNIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.8874
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "COMPL. 1 FREQUÊNCIA MÍNIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.8874
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "COMPL. 1 FREQUÊNCIA MÍNIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.8874
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "COMPL. 1 FREQUÊNCIA MÍNIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 9.2929
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "PELO MENOS DUAS BOMBAS OK"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 8.9631
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "TODAS AS BOMBAS"
    varAttribs1(1).TextString = "DESLIGADAS"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 8.963
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "PARTIDA DE GRUPO HABILITADA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 10.7926
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "COMPL. 1 FREQUÊNCIA MÁXIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.0443
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "COMPL. 1 FREQUÊNCIA MÁXIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.0443
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "COMPL. 1 FREQUÊNCIA MÁXIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.7567
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "COMPL. 2 FREQUÊNCIA MÍNIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.0443
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "COMPL. 2 FREQUÊNCIA MÍNIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.0443
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "COMPL. 2 FREQUÊNCIA MÍNIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.0443
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "COMPL. 2 FREQUÊNCIA MÍNIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 10.0467
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "PELO MENOS TRÊS BOMBAS OK"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 316.0123
    objInsertionPoint(1) = objInsertionPoint(1) + 59.6662
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "LIGA COMPLEMENTAR 2"
    varAttribs1(2).TextString = CStr(pg) + "B"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 0.1607
    objInsertionPoint(1) = objInsertionPoint(1) + 135.4165
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "LIGA COMPLEMENTAR 1"
    varAttribs1(2).TextString = CStr(pg) + "A"
    
    pg = pg + 1
    
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DL" Then
            If varAttribs1(3).TextString = CStr(pg) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - REVEZAMENTO DE BOMBAS"
                addpg = 1
            End If
        End If
    Next objBRef1
        
    If addpg = 0 Then
        addpage objSelection10, area, clp, "DL", pg
    End If
        
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DL" Then
            If varAttribs1(3).TextString = CStr(pg) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - REVEZAMENTO DE BOMBAS"
                addpg = 0
            End If
        End If
    Next objBRef1
        
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "REVEZAMENTO_4BOMBAS5_R00", 1, 1, 1, 0)
    ExpBlock objBRef1
    
    objInsertionPoint(0) = varInsertionPoint(0) + 46.9397
    objInsertionPoint(1) = varInsertionPoint(1) - 21.7706
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "PV > SP"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.9999
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "COMPL. 2 FREQUÊNCIA MÁXIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 9.8507
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "PV > SP"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 12
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "COMPL. 2 FREQUÊNCIA MÁXIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 10.5659
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "PV > SP"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 12
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "COMPL. 2 FREQUÊNCIA MÁXIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 22.0369
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "FREQUÊNCIA MÍNIMA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 32.1144
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "LIGA COMPLEMENTAR 2"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 15.2185
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "TODAS AS BOMBAS OK"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 322.8204
    objInsertionPoint(1) = objInsertionPoint(1) - 35.3952
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "DESABILITA BOMBA RESERVA"
    varAttribs1(2).TextString = CStr(pg) + "B"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) + 134.8392
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "LIGA RESERVA"
    varAttribs1(2).TextString = CStr(pg) + "A"
    
    pg = pg + 1
    
    pgdc = CLng(shtObj3.Cells(13, x + 5).Value) + 20
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DC" Then
            If varAttribs1(3).TextString = CStr(pgdc) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - SELEÇÃO DE BOMBAS"
                addpg = 1
            End If
        End If
    Next objBRef1
            
    If addpg = 0 Then
        addpage objSelection10, area, clp, "DC", pgdc
    End If
            
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
                
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DC" Then
            If varAttribs1(3).TextString = CStr(pgdc) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - SELEÇÃO DE BOMBAS"
                addpg = 0
            End If
        End If
    Next objBRef1
            
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "SELECAO_4BOMBAS_R00", 1, 1, 1, 0)
    ExpBlock objBRef1
    
    objInsertionPoint(0) = varInsertionPoint(0) + 84.0072
    objInsertionPoint(1) = varInsertionPoint(1) - 84.8039
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "COMANDO_CXS", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "E" + area + clp + UCase(shtObj3.Cells(7, x + 3).Value) + "B01" + "HS05"
    varAttribs1(1).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(2).TextString = "PRINCIPAL"
    varAttribs1(3).TextString = "%M46"
            
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 35.554
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "COMANDO_CXS", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "E" + area + clp + UCase(shtObj3.Cells(7, x + 3).Value) + "B02" + "HS05"
    varAttribs1(1).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(2).TextString = "PRINCIPAL"
    varAttribs1(3).TextString = "%M47"
            
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 35.554
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "COMANDO_CXS", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "E" + area + clp + UCase(shtObj3.Cells(7, x + 3).Value) + "B03" + "HS05"
    varAttribs1(1).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(2).TextString = "PRINCIPAL"
    varAttribs1(3).TextString = "%M48"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 36.2663
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "COMANDO_CXS", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "E" + area + clp + UCase(shtObj3.Cells(7, x + 3).Value) + "B04" + "HS05"
    varAttribs1(1).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(2).TextString = "PRINCIPAL"
    varAttribs1(3).TextString = "%M49"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 95.2901
    objInsertionPoint(1) = objInsertionPoint(1) - 51.8244
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "TEMPO DELAY"
    varAttribs1(2).TextString = CStr(pgdc) + "A"
    varAttribs1(3).TextString = "%MF1080"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 63.5496
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "TEMPO DELAY"
    varAttribs1(2).TextString = CStr(pgdc) + "B"
    varAttribs1(3).TextString = "%MF1080"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 90.3272
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "TEMPO DELAY"
    varAttribs1(2).TextString = CStr(pgdc) + "C"
    varAttribs1(3).TextString = "%MF1080"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 44.2451
    objInsertionPoint(1) = objInsertionPoint(1) + 47.5826
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "INICIA COMO PRINCIPAL"
    varAttribs1(2).TextString = CStr(pgdc) + "D"
    varAttribs1(3).TextString = "%MF1080"
    varAttribs1(4).TextString = "DIGITAL"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    pgdc = pgdc + 1
    
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DC" Then
            If varAttribs1(3).TextString = CStr(pgdc) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - SELEÇÃO DE BOMBAS"
                addpg = 1
            End If
        End If
    Next objBRef1
            
    If addpg = 0 Then
        addpage objSelection10, area, clp, "DC", pgdc
    End If
            
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
                
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DC" Then
            If varAttribs1(3).TextString = CStr(pgdc) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - SELEÇÃO DE BOMBAS"
                addpg = 0
            End If
        End If
    Next objBRef1
            
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "SELECAO_4BOMBAS2_R00", 1, 1, 1, 0)
    ExpBlock objBRef1
    
    objInsertionPoint(0) = varInsertionPoint(0) + 41.7431
    objInsertionPoint(1) = varInsertionPoint(1) - 52.7804
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
    varAttribs1(1).TextString = "PARTIDA DE GRUPO HABILITADA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 0.0014
    objInsertionPoint(1) = objInsertionPoint(1) - 63.6023
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "OK PARA OPERAÇÃO = 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 0.5185
    objInsertionPoint(1) = objInsertionPoint(1) - 11.0336
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "OK PARA OPERAÇÃO = 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 11.0336
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "OK PARA OPERAÇÃO = 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 12.7297
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "SEL. COMO PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 19.9156
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "SEL. COMO PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 0.536
    objInsertionPoint(1) = objInsertionPoint(1) - 20.1777
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DL", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(31, x).Value)
    varAttribs1(1).TextString = "RESET TEMPO DE EXISTÊNCIA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 0.2551
    objInsertionPoint(1) = objInsertionPoint(1) - 12
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "SEL. COMO PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 137.6513
    objInsertionPoint(1) = objInsertionPoint(1) - 33.4108
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "TEMPO EXISTÊNCIA"
    varAttribs1(2).TextString = CStr(pgdc) + "A"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 103.4453
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "TEMPO EXISTÊNCIA"
    varAttribs1(2).TextString = CStr(pgdc) + "B"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 94.2645
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "TEMPO EXISTÊNCIA"
    varAttribs1(2).TextString = CStr(pgdc) + "C"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 6.8278
    objInsertionPoint(1) = objInsertionPoint(1) + 218.4831
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "TEMPO DELAY"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 94.2645
    objInsertionPoint(1) = objInsertionPoint(1) + 0.3871
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "TEMPO DELAY"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 103.4453
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "TEMPO DELAY"
    varAttribs1(2).TextString = "-"
    
    pgdc = pgdc + 1
    
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DC" Then
            If varAttribs1(3).TextString = CStr(pgdc) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - SELEÇÃO DE BOMBAS"
                addpg = 1
            End If
        End If
    Next objBRef1
            
    If addpg = 0 Then
        addpage objSelection10, area, clp, "DC", pgdc
    End If
            
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
                
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DC" Then
            If varAttribs1(3).TextString = CStr(pgdc) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - SELEÇÃO DE BOMBAS"
                addpg = 0
            End If
        End If
    Next objBRef1
    
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "SELECAO_4BOMBAS3_R00", 1, 1, 1, 0)
    ExpBlock objBRef1
    
    objInsertionPoint(0) = varInsertionPoint(0) + 43.8335
    objInsertionPoint(1) = varInsertionPoint(1) - 83.9049
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "SEL. COMO PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 28.7501
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "SEL. COMO COMPL. 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 15.5557
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "SEL. COMO PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 28.7501
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "SEL. COMO COMPL. 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 15.5557
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "SEL. COMO PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 28.7501
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "SEL. COMO COMPL. 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 117.9115
    objInsertionPoint(1) = objInsertionPoint(1) - 30.3056
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "TEMPO PARA SEL. COMPL. 1"
    varAttribs1(2).TextString = CStr(pgdc) + "A"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 23.481
    objInsertionPoint(1) = objInsertionPoint(1) - 13.0699
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "TEMPO PARA SEL. COMPL. 2"
    varAttribs1(2).TextString = CStr(pgdc) + "B"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 65.2038
    objInsertionPoint(1) = objInsertionPoint(1) + 13.0699
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "TEMPO PARA SEL. COMPL. 1"
    varAttribs1(2).TextString = CStr(pgdc) + "C"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 23.481
    objInsertionPoint(1) = objInsertionPoint(1) - 13.0699
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "TEMPO PARA SEL. COMPL. 2"
    varAttribs1(2).TextString = CStr(pgdc) + "D"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 65.2038
    objInsertionPoint(1) = objInsertionPoint(1) + 13.0699
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "TEMPO PARA SEL. COMPL. 1"
    varAttribs1(2).TextString = CStr(pgdc) + "E"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 23.481
    objInsertionPoint(1) = objInsertionPoint(1) - 13.0699
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "TEMPO PARA SEL. COMPL. 2"
    varAttribs1(2).TextString = CStr(pgdc) + "F"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 33.17
    objInsertionPoint(1) = objInsertionPoint(1) + 211.2921
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "TEMPO EXISTÊNCIA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 88.6848
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "TEMPO EXISTÊNCIA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 88.6848
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "TEMPO EXISTÊNCIA"
    varAttribs1(2).TextString = "-"
    
    pgdc = pgdc + 1
    
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DC" Then
            If varAttribs1(3).TextString = CStr(pgdc) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - SELEÇÃO DE BOMBAS"
                addpg = 1
            End If
        End If
    Next objBRef1
            
    If addpg = 0 Then
        addpage objSelection10, area, clp, "DC", pgdc
    End If
            
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
                
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DC" Then
            If varAttribs1(3).TextString = CStr(pgdc) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - SELEÇÃO DE BOMBAS"
                addpg = 0
            End If
        End If
    Next objBRef1
            
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "SELECAO_4BOMBAS4_R00", 1, 1, 1, 0)
    ExpBlock objBRef1
    
    objInsertionPoint(0) = varInsertionPoint(0) + 62.8096
    objInsertionPoint(1) = varInsertionPoint(1) - 29.837
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "TEMPO EXISTÊNCIA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 51.9945
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "TEMPO EXISTÊNCIA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 51.5033
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "TEMPO EXISTÊNCIA"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 75.5362
    objInsertionPoint(1) = objInsertionPoint(1) - 214.0877
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "MAIOR TEMPO EXISTÊNCIA"
    varAttribs1(1).TextString = "PRINCIPAL"
    varAttribs1(2).TextString = CStr(pgdc) + "A"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 196.6429
    objInsertionPoint(1) = objInsertionPoint(1) - 0.4939
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "BOMBA SELECIONADA"
    varAttribs1(1).TextString = "PRINCIPAL"
    varAttribs1(2).TextString = CStr(pgdc) + "B"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    pgdc = pgdc + 1
    
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DC" Then
            If varAttribs1(3).TextString = CStr(pgdc) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - SELEÇÃO DE BOMBAS"
                addpg = 1
            End If
        End If
    Next objBRef1
            
    If addpg = 0 Then
        addpage objSelection10, area, clp, "DC", pgdc
    End If
            
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
                
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DC" Then
            If varAttribs1(3).TextString = CStr(pgdc) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - SELEÇÃO DE BOMBAS"
                addpg = 0
            End If
        End If
    Next objBRef1
            
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "SELECAO_4BOMBAS4_R00", 1, 1, 1, 0)
    ExpBlock objBRef1
    
    objInsertionPoint(0) = varInsertionPoint(0) + 62.8096
    objInsertionPoint(1) = varInsertionPoint(1) - 29.837
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "TEMPO PARA SEL. COMPL. 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 51.9945
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "TEMPO PARA SEL. COMPL. 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 51.5033
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "TEMPO PARA SEL. COMPL. 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 75.5362
    objInsertionPoint(1) = objInsertionPoint(1) - 214.0877
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "MAIOR TEMPO EXISTÊNCIA"
    varAttribs1(1).TextString = "COMPLEMENTAR 1"
    varAttribs1(2).TextString = CStr(pgdc) + "A"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 196.6429
    objInsertionPoint(1) = objInsertionPoint(1) - 0.4939
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "BOMBA SELECIONADA"
    varAttribs1(1).TextString = "COMPLEMENTAR 1"
    varAttribs1(2).TextString = CStr(pgdc) + "B"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    pgdc = pgdc + 1
    
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DC" Then
            If varAttribs1(3).TextString = CStr(pgdc) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - SELEÇÃO DE BOMBAS"
                addpg = 1
            End If
        End If
    Next objBRef1
            
    If addpg = 0 Then
        addpage objSelection10, area, clp, "DC", pgdc
    End If
            
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
                
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DC" Then
            If varAttribs1(3).TextString = CStr(pgdc) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - SELEÇÃO DE BOMBAS"
                addpg = 0
            End If
        End If
    Next objBRef1
            
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "SELECAO_4BOMBAS4_R00", 1, 1, 1, 0)
    ExpBlock objBRef1
    
    objInsertionPoint(0) = varInsertionPoint(0) + 62.8096
    objInsertionPoint(1) = varInsertionPoint(1) - 29.837
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "TEMPO PARA SEL. COMPL. 2"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 51.9945
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "TEMPO PARA SEL. COMPL. 2"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 51.5033
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "TEMPO PARA SEL. COMPL. 2"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 75.5362
    objInsertionPoint(1) = objInsertionPoint(1) - 214.0877
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "MAIOR TEMPO EXISTÊNCIA"
    varAttribs1(1).TextString = "COMPLEMENTAR 2"
    varAttribs1(2).TextString = CStr(pgdc) + "A"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 196.6429
    objInsertionPoint(1) = objInsertionPoint(1) - 0.4939
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "BOMBA SELECIONADA"
    varAttribs1(1).TextString = "COMPLEMENTAR 2"
    varAttribs1(2).TextString = CStr(pgdc) + "B"
    varAttribs1(3).TextString = "%MF1084"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    pgdc = pgdc + 1
    
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DC" Then
            If varAttribs1(3).TextString = CStr(pgdc) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - SELEÇÃO DE BOMBAS"
                addpg = 1
            End If
        End If
    Next objBRef1
            
    If addpg = 0 Then
        addpage objSelection10, area, clp, "DC", pgdc
    End If
            
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
                
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(0).TextString = "DC" Then
            If varAttribs1(3).TextString = CStr(pgdc) Then
                varInsertionPoint(0) = objBRef1.InsertionPoint(0)
                varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - SELEÇÃO DE BOMBAS"
                addpg = 0
            End If
        End If
    Next objBRef1
            
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "SELECAO_4BOMBAS5_R00", 1, 1, 1, 0)
    ExpBlock objBRef1
    
    objInsertionPoint(0) = varInsertionPoint(0) + 35.8457
    objInsertionPoint(1) = varInsertionPoint(1) - 36.79
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "MAIOR TEMPO EXISTÊNCIA"
    varAttribs1(1).TextString = "PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 45.5544
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "BOMBA SELECIONADA"
    varAttribs1(1).TextString = "PRINCIPAL"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 64.3509
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "MAIOR TEMPO EXISTÊNCIA"
    varAttribs1(1).TextString = "COMPLEMENTAR 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 45.5544
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "BOMBA SELECIONADA"
    varAttribs1(1).TextString = "COMPLEMENTAR 1"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 64.3508
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "MAIOR TEMPO EXISTÊNCIA"
    varAttribs1(1).TextString = "COMPLEMENTAR 2"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 45.5545
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "IN_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = "BOMBA SELECIONADA"
    varAttribs1(1).TextString = "COMPLEMENTAR 2"
    varAttribs1(2).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 140.6829
    objInsertionPoint(1) = objInsertionPoint(1) - 49.8792
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "SEL. COMO PRINCIPAL"
    varAttribs1(2).TextString = CStr(pgdc) + "A"
    varAttribs1(3).TextString = "%MF1088"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) - 0.0358
    objInsertionPoint(1) = objInsertionPoint(1) - 28.6285
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "SEL. COMO PRINCIPAL"
    varAttribs1(2).TextString = CStr(pgdc) + "B"
    varAttribs1(3).TextString = "%MF1088"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 28.4671
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "SEL. COMO PRINCIPAL"
    varAttribs1(2).TextString = CStr(pgdc) + "C"
    varAttribs1(3).TextString = "%MF1088"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 109.9053
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "SEL. COMO COMPL. 1"
    varAttribs1(2).TextString = CStr(pgdc) + "F"
    varAttribs1(3).TextString = "%MF1088"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) + 28.4671
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "SEL. COMO COMPL. 1"
    varAttribs1(2).TextString = CStr(pgdc) + "E"
    varAttribs1(3).TextString = "%MF1088"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) + 28.4671
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "SEL. COMO COMPL. 1"
    varAttribs1(2).TextString = CStr(pgdc) + "D"
    varAttribs1(3).TextString = "%MF1088"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0) + 109.9053
    objInsertionPoint(1) = objInsertionPoint(1)
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(13, x).Value)
    varAttribs1(1).TextString = "SEL. COMO COMPL. 2"
    varAttribs1(2).TextString = CStr(pgdc) + "G"
    varAttribs1(3).TextString = "%MF1088"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 28.4671
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(19, x).Value)
    varAttribs1(1).TextString = "SEL. COMO COMPL. 2"
    varAttribs1(2).TextString = CStr(pgdc) + "H"
    varAttribs1(3).TextString = "%MF1088"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    objInsertionPoint(0) = objInsertionPoint(0)
    objInsertionPoint(1) = objInsertionPoint(1) - 28.4671
    objInsertionPoint(2) = 0
    Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DC", 1, 1, 1, 0)
    varAttribs1 = objBRef1.GetAttributes
    varAttribs1(0).TextString = UCase(shtObj3.Cells(25, x).Value)
    varAttribs1(1).TextString = "SEL. COMO COMPL. 2"
    varAttribs1(2).TextString = CStr(pgdc) + "I"
    varAttribs1(3).TextString = "%MF1088"
    varAttribs1(4).TextString = "ANALÓGICO"
    varAttribs1(5).TextString = "-"
    varAttribs1(6).TextString = "-"
    
    JUNK = DeleteSelectionSets()
    
End Sub
