Public excelApp As Object
Public wdkObj As Object
Public shtObj As Object

Sub CommandButton1_Click()
    On Error Resume Next
    UserForm1.Hide
    Err.Clear
    Set excelApp = GetObject("D:\Teste.xlsx", "Excel.Application")
    If Err <> 0 Then
        Err.Clear
        Set excelApp = CreateObject("Excel.Application")
        If Err <> 0 Then
            MsgBox "Não foi possivel iniciar o Excel", vbExclamation
            End
        End If
    End If
    excelApp.Visible = True
    Set wbkObj = Workbooks.Open("D:\Teste.xlsx")
    Set shtObj = excelApp.Worksheets(1)
    UserForm1.show
End Sub
Sub CommandButton2_Click()
    
    Dim objSelection10 As AcadSelectionSet
    Dim objSelection11 As AcadSelectionSet
    Dim objSelection12 As AcadSelectionSet
    Dim objSelection13 As AcadSelectionSet
    Dim objSelection14 As AcadSelectionSet
    Dim objBRef1 As AcadBlockReference
    Dim objBRef2 As AcadBlockReference
    Dim varInsertionPoint(2) As Double
    Dim linePointSTR(2) As Double
    Dim linePointEND(2) As Double
    Dim objInsertionPoint(2) As Double
    Dim txtfolha As acadText
    Dim varAttribs1 As Variant
    Dim varAttribs2 As Variant
    Dim clp As Variant
    Dim area As Variant
    Dim x, y, z As Integer
    
    On Error Resume Next
    UserForm1.Hide
    Err.Clear
    Set excelApp = GetObject("D:\Teste.xlsx", "Excel.Application")
    excelApp.Visible = True
    Set shtObj = excelApp.Worksheets(1)
    Set shtObj2 = excelApp.Worksheets(2)
    Set shtObj3 = excelApp.Worksheets(3)
    Set shtObj4 = excelApp.Worksheets(4)
    
    ThisDrawing.ActiveLayer = ThisDrawing.Layers("0")
    
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
    JUNK = GetObjectSelectionSet(CStr("OUT_REF_DL"), objSelection11)
    JUNK = GetObjectSelectionSet(CStr("IN_REF_DL"), objSelection12)
    JUNK = GetObjectSelectionSet(CStr("OUT_REF_DC"), objSelection13)
    JUNK = GetObjectSelectionSet(CStr("IN_REF_DC"), objSelection14)
      
    clp = UCase(shtObj.Cells(10, 2).Value)
    area = UCase(shtObj.Cells(10, 3).Value)
        
    For Each objBRef1 In objSelection10
    
        varAttribs1 = objBRef1.GetAttributes
        varAttribs1(2).TextString = clp
        varAttribs1(1).TextString = area
        varAttribs1(4).TextString = UCase(CStr(shtObj.Cells(7, 2).Value + " - " + shtObj.Cells(7, 3).Value + " - " + shtObj.Cells(7, 4).Value + " \ DIAGRAMA LÓGICO"))
    
    Next objBRef1
    
    varInsertionPoint(0) = 55
    varInsertionPoint(1) = -37
    varInsertionPoint(2) = 0
    a = CLng(shtObj.Cells(6, 8).Value)
    b = 0
    C = 1
    d = 1
    pg = 1
    addpg = 0
    
    ED = 0
    ED = shtObj.Cells(5, 8).Value
    For y = 1 To ED
        
        For Each objBRef1 In objSelection10
            varAttribs1 = objBRef1.GetAttributes
            If varAttribs1(0).TextString = "DL" Then
                If varAttribs1(3).TextString = CStr(pg) Then
                    varAttribs1(5).TextString = clp + " - ENTRADAS DIGITAIS"
                End If
            End If
        Next objBRef1
        
        Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "ENTRADA_DIGITAL", 1, 1, 1, 0)
        varAttribs1 = objBRef1.GetAttributes
        varAttribs1(6).TextString = "%I" + CStr(a) + "." + CStr(b)
        For x = 2 To 10000
            If varAttribs1(6).TextString = shtObj2.Cells(x, 8).Value Then
                Exit For
            End If
        Next x
        varAttribs1(3).TextString = UCase(shtObj2.Cells(x, 4).Value)
        If shtObj2.Cells(x, 15).Value = "true" Then
            varAttribs1(4).TextString = UCase(shtObj2.Cells(x, 6).Value + " = 1")
        Else
            If shtObj2.Cells(x, 15).Value = "false" Then
                varAttribs1(4).TextString = UCase(shtObj2.Cells(x, 6).Value + " = 0")
            Else
                varAttribs1(4).TextString = UCase(shtObj2.Cells(x, 6).Value)
            End If
        End If
        
        varAttribs1(0).TextString = UCase(shtObj2.Cells(x, 12).Value)
        varAttribs1(1).TextString = UCase(shtObj2.Cells(x, 13).Value)
        varAttribs1(2).TextString = UCase(shtObj2.Cells(x, 11).Value)

        b = b + 1
        If b = 8 Then
            a = a + 1
            b = 0
        End If
        
        If shtObj2.Cells(x, 14).Value <> "Escreva a Tag do Alarme/Estado" Then
            For z = 2 To 1000
                If shtObj2.Cells(z, 5).Value = shtObj2.Cells(x, 14).Value And z <> x Then
                    Exit For
                End If
            Next z
        End If
        
        linePointSTR(0) = varInsertionPoint(0) + 53.933
        linePointSTR(1) = varInsertionPoint(1) - 11.4927
        linePointSTR(2) = 0
        linePointEND(0) = linePointSTR(0) + 65
        linePointEND(1) = linePointSTR(1)
        linePointEND(2) = 0
        ThisDrawing.ModelSpace.AddLine(linePointSTR, linePointEND).Layer = "FIACAO"
        If shtObj2.Cells(x, 14).Value <> "Escreva a Tag do Alarme/Estado" Then
            If shtObj2.Cells(z, 9).Value = "Alarme" Then
                If shtObj2.Cells(z, 15).Value = "FALSE" Then
                    linePointSTR(0) = linePointSTR(0) + 15.6961
                    linePointSTR(1) = linePointSTR(1)
                    linePointSTR(2) = 0
                    linePointEND(0) = linePointSTR(0)
                    linePointEND(1) = linePointSTR(1) + 18.6121
                    linePointEND(2) = 0
                    ThisDrawing.ModelSpace.AddLine(linePointSTR, linePointEND).Layer = "FIACAO"
                    ThisDrawing.ModelSpace.InsertBlock(linePointSTR, "CROSS_L", 1.4, 1.4, 1.4, 0).Layer = "DESENHO_LINHAS"
                    linePointSTR(0) = linePointEND(0) + 49.3039
                    linePointSTR(1) = linePointEND(1) - 18.6121
                    linePointSTR(2) = 0
                Else
                    linePointSTR(0) = linePointSTR(0) + 15.6961
                    linePointSTR(1) = linePointSTR(1)
                    linePointSTR(2) = 0
                    linePointEND(0) = linePointSTR(0)
                    linePointEND(1) = linePointSTR(1) + 7.4505
                    linePointEND(2) = 0
                    ThisDrawing.ModelSpace.AddLine(linePointSTR, linePointEND).Layer = "FIACAO"
                    ThisDrawing.ModelSpace.InsertBlock(linePointSTR, "CROSS_L", 1.4, 1.4, 1.4, 0).Layer = "DESENHO_LINHAS"
                    
                    linePointSTR(0) = linePointSTR(0)
                    linePointSTR(1) = linePointEND(1) + 2.6737
                    linePointSTR(2) = 0
                    ThisDrawing.ModelSpace.AddCircle(linePointSTR, 2.6737).Layer = "FIACAO"
                    
                    linePointSTR(0) = linePointSTR(0)
                    linePointSTR(1) = linePointSTR(1) + 2.6737
                    linePointSTR(2) = 0
                    linePointEND(0) = linePointSTR(0)
                    linePointEND(1) = linePointSTR(1) + 6.2949
                    linePointEND(2) = 0
                    ThisDrawing.ModelSpace.AddLine(linePointSTR, linePointEND).Layer = "FIACAO"
                    
                    linePointSTR(0) = linePointSTR(0) - 1.94
                    linePointSTR(1) = linePointSTR(1) - 2.6737
                    linePointSTR(2) = 0
                    linePointEND(0) = linePointSTR(0) + 3.8801
                    linePointEND(1) = linePointSTR(1)
                    linePointEND(2) = 0
                    ThisDrawing.ModelSpace.AddLine(linePointSTR, linePointEND).Layer = "TEXTPAREXTERNA"
                    
                    linePointEND(0) = linePointSTR(0) + 1.94
                    linePointEND(1) = linePointSTR(1) + 8.9686
                    linePointEND(2) = 0
                    linePointSTR(0) = linePointEND(0) + 49.3039
                    linePointSTR(1) = linePointEND(1) - 19.0928
                    linePointSTR(2) = 0
                    
                End If
                
                Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(linePointEND, "ALARME", 1, 1, 1, 0)
                varAttribs1 = objBRef1.GetAttributes
                varAttribs1(0).TextString = UCase(shtObj2.Cells(z, 5).Value)
                varAttribs1(1).TextString = UCase(shtObj2.Cells(z, 4).Value)
                varAttribs1(2).TextString = UCase(shtObj2.Cells(z, 6).Value)
                varAttribs1(3).TextString = "%MW0:X0"
                linePointEND(0) = linePointSTR(0)
                linePointEND(1) = linePointSTR(1)
                linePointEND(2) = 0
    
            End If
            If shtObj2.Cells(z, 9).Value = "Estado" Then
                If shtObj2.Cells(z, 15).Value = 1 Then
                    linePointSTR(0) = linePointSTR(0) + 15.6961
                    linePointSTR(1) = linePointSTR(1)
                    linePointSTR(2) = 0
                    linePointEND(0) = linePointSTR(0)
                    linePointEND(1) = linePointSTR(1) + 18.6121
                    linePointEND(2) = 0
                    ThisDrawing.ModelSpace.AddLine(linePointSTR, linePointEND).Layer = "FIACAO"
                    ThisDrawing.ModelSpace.InsertBlock(linePointSTR, "CROSS_L", 1.4, 1.4, 1.4, 0).Layer = "DESENHO_LINHAS"
                    linePointSTR(0) = linePointEND(0) + 49.3039
                    linePointSTR(1) = linePointEND(1) - 18.6121
                    linePointSTR(2) = 0
                Else
                    linePointSTR(0) = linePointSTR(0) + 15.6961
                    linePointSTR(1) = linePointSTR(1)
                    linePointSTR(2) = 0
                    linePointEND(0) = linePointSTR(0)
                    linePointEND(1) = linePointSTR(1) + 7.4505
                    linePointEND(2) = 0
                    ThisDrawing.ModelSpace.AddLine(linePointSTR, linePointEND).Layer = "FIACAO"
                    ThisDrawing.ModelSpace.InsertBlock(linePointSTR, "CROSS_L", 1.4, 1.4, 1.4, 0).Layer = "DESENHO_LINHAS"
                    
                    linePointSTR(0) = linePointSTR(0)
                    linePointSTR(1) = linePointEND(1) + 2.6737
                    linePointSTR(2) = 0
                    ThisDrawing.ModelSpace.AddCircle(linePointSTR, 2.6737).Layer = "FIACAO"
                    
                    linePointSTR(0) = linePointSTR(0)
                    linePointSTR(1) = linePointSTR(1) + 2.6737
                    linePointSTR(2) = 0
                    linePointEND(0) = linePointSTR(0)
                    linePointEND(1) = linePointSTR(1) + 6.2949
                    linePointEND(2) = 0
                    ThisDrawing.ModelSpace.AddLine(linePointSTR, linePointEND).Layer = "FIACAO"
                    
                    linePointSTR(0) = linePointSTR(0) - 1.94
                    linePointSTR(1) = linePointSTR(1) - 2.6737
                    linePointSTR(2) = 0
                    linePointEND(0) = linePointSTR(0) + 3.8801
                    linePointEND(1) = linePointSTR(1)
                    linePointEND(2) = 0
                    ThisDrawing.ModelSpace.AddLine(linePointSTR, linePointEND).Layer = "TEXTPAREXTERNA"
                    
                    linePointEND(0) = linePointSTR(0) + 1.94
                    linePointEND(1) = linePointSTR(1) + 8.9686
                    linePointEND(2) = 0
                    linePointSTR(0) = linePointEND(0) + 49.3039
                    linePointSTR(1) = linePointEND(1) - 19.0928
                    linePointSTR(2) = 0
                
                End If
                Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(linePointEND, "ESTADO", 1, 1, 1, 0)
                varAttribs1 = objBRef1.GetAttributes
                varAttribs1(0).TextString = UCase(shtObj2.Cells(z, 5).Value)
                varAttribs1(1).TextString = UCase(shtObj2.Cells(z, 4).Value)
                varAttribs1(2).TextString = UCase(shtObj2.Cells(z, 6).Value)
                varAttribs1(3).TextString = "%MW0:X0"
                linePointEND(0) = linePointSTR(0)
                linePointEND(1) = linePointSTR(1)
                linePointEND(2) = 0
                
            End If
        End If
        
        Set objBRef2 = ThisDrawing.ModelSpace.InsertBlock(linePointEND, "OUT_REF_DL", 1, 1, 1, 0)
        varAttribs2 = objBRef2.GetAttributes
        varAttribs2(0).TextString = UCase(shtObj2.Cells(x, 4).Value)
        If shtObj2.Cells(x, 15).Value = "true" Then
            varAttribs2(1).TextString = UCase(shtObj2.Cells(x, 6).Value + " = 1")
        Else
            If shtObj2.Cells(x, 15).Value = "false" Then
                varAttribs2(1).TextString = UCase(shtObj2.Cells(x, 6).Value + " = 0")
            Else
                varAttribs2(1).TextString = UCase(shtObj2.Cells(x, 6).Value)
            End If
        End If
        varAttribs2(4).TextString = "-"
        varAttribs2(5).TextString = "-"
        Select Case d
        Case 1
            varAttribs2(2).TextString = CStr(C) + "A"
        Case 2
            varAttribs2(2).TextString = CStr(C) + "B"
        Case 3
            varAttribs2(2).TextString = CStr(C) + "C"
        Case 4
            varAttribs2(2).TextString = CStr(C) + "D"
        Case 5
            varAttribs2(2).TextString = CStr(C) + "E"
        Case 6
            varAttribs2(2).TextString = CStr(C) + "F"
        Case 7
            varAttribs2(2).TextString = CStr(C) + "G"
        Case 8
            varAttribs2(2).TextString = CStr(C) + "H"
            C = C + 1
            d = 0
        End Select
        
        d = d + 1
        varInsertionPoint(1) = varInsertionPoint(1) - 60
        If y Mod 4 = 0 Then
            If y Mod 8 = 0 Then
                varInsertionPoint(0) = varInsertionPoint(0) + 287.5
                pg = pg + 1
            Else
                varInsertionPoint(0) = varInsertionPoint(0) + 182.5
            End If
            varInsertionPoint(1) = varInsertionPoint(1) + 240
        End If
        objInsertionPoint(0) = varInsertionPoint(0) + 46.703
        objInsertionPoint(1) = varInsertionPoint(1) - 85.0757
        objInsertionPoint(2) = 0
    
        
    Next y
    
    entradasanalog area, clp
    
    x = 2
    Ga = 0
    Ga = shtObj.Cells(17, 3).Value
    
    For y = 1 To Ga
        
        pg = CLng(shtObj3.Cells(7, x + 5))
        JUNK = CreateSelectionSets()
        JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
        
        For Each objBRef1 In objSelection10
            
            varAttribs1 = objBRef1.GetAttributes
            If varAttribs1(0).TextString = "DL" Then
                If varAttribs1(3).TextString = CStr(pg) Then
                    varInsertionPoint(0) = 0
                    varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                    varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                    addpg = 1
                End If
            End If
            
        Next objBRef1
        
        If addpg = 0 Then
            addpage objSelection10, area, clp, "DL", pg
        End If
        
        JUNK = CreateSelectionSets()
        JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
        
        For Each objBRef1 In objSelection10
        
            varAttribs1 = objBRef1.GetAttributes
            If varAttribs1(0).TextString = "DL" Then
                If varAttribs1(3).TextString = CStr(pg) Then
                    varInsertionPoint(0) = 0
                    varInsertionPoint(1) = objBRef1.InsertionPoint(1)
                    varInsertionPoint(2) = objBRef1.InsertionPoint(2)
                    varAttribs1(5).TextString = UCase(shtObj3.Cells(7, x).Value) + " - INTERTRAV. DE PROCESSO"
                    addpg = 0
                End If
            End If
            
        Next objBRef1
        
        Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "INTERTRAV_PROCESS", 1, 1, 1, 0)
        ExpBlock objBRef1
            
        objInsertionPoint(0) = varInsertionPoint(0) + 46.703
        objInsertionPoint(1) = varInsertionPoint(1) - 85.0757
        objInsertionPoint(2) = 0
        ThisDrawing.ModelSpace.AddText(UCase(shtObj3.Cells(7, x).Value), objInsertionPoint, 2).Layer = "DESENHO_TEXTO"
            
        objInsertionPoint(0) = varInsertionPoint(0) + 98.7316
        objInsertionPoint(1) = varInsertionPoint(1) - 70.4891
        objInsertionPoint(2) = 0
        Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "COMANDO_CXS", 1, 1, 1, 0)
        varAttribs1 = objBRef1.GetAttributes
        varAttribs1(0).TextString = "E" + area + clp + UCase(shtObj3.Cells(7, x + 3).Value) + "HS01"
        varAttribs1(1).TextString = UCase(shtObj3.Cells(7, x).Value)
        varAttribs1(2).TextString = "HABILITA PARTIDA DE GRUPO"
        varAttribs1(3).TextString = "%M25"
            
        objInsertionPoint(0) = varInsertionPoint(0) + 147.349
        objInsertionPoint(1) = varInsertionPoint(1) - 56.6285
        objInsertionPoint(2) = 0
        Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "ESTADO", 1, 1, 1, 0)
        varAttribs1 = objBRef1.GetAttributes
        varAttribs1(0).TextString = "E" + area + clp + UCase(shtObj3.Cells(7, x + 3).Value) + "HS01"
        varAttribs1(1).TextString = UCase(shtObj3.Cells(7, x).Value)
        varAttribs1(2).TextString = "OPERAÇÃO DESABILITADA"
        varAttribs1(3).TextString = "%MW0:X0"
            
        objInsertionPoint(0) = varInsertionPoint(0) + 372.1101
        objInsertionPoint(1) = varInsertionPoint(1) - 57.7001
        objInsertionPoint(2) = 0
        Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
        varAttribs1 = objBRef1.GetAttributes
        varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
        varAttribs1(1).TextString = "PARTIDA DE GRUPO HABILITADA"
        varAttribs1(2).TextString = CStr(pg) + "A"
        varAttribs1(3).TextString = "%M216"
        varAttribs1(4).TextString = "-"
        varAttribs1(5).TextString = "-"
        
        objInsertionPoint(0) = varInsertionPoint(0) + 372.1101
        objInsertionPoint(1) = varInsertionPoint(1) - 75.7212
        objInsertionPoint(2) = 0
        Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(objInsertionPoint, "OUT_REF_DL", 1, 1, 1, 0)
        varAttribs1 = objBRef1.GetAttributes
        varAttribs1(0).TextString = UCase(shtObj3.Cells(7, x).Value)
        varAttribs1(1).TextString = "INTERTRAVAMENTO DE PROCESSO"
        varAttribs1(2).TextString = CStr(pg) + "B"
        varAttribs1(3).TextString = "%M217"
        varAttribs1(4).TextString = "-"
        varAttribs1(5).TextString = "-"
            
        pg = pg + 1
            
        b = 0
        b = CLng(shtObj3.Cells(7, x + 2).Value)
        z = 13
        pe = pg
        For i = 1 To b
            If shtObj3.Cells(z + 2, x + 5).Value = "Sim" Then
                pg = pg + 2
            End If
            z = z + 6
        Next i

        If shtObj3.Cells(7, x + 4).Value = "Sim, 2 Bombas" Then
            revez2Bombas area, clp, x, pg
        End If
            
        If shtObj3.Cells(7, x + 4).Value = "Sim, 3 Bombas" Then
            revez3bombas area, clp, x, pg
        End If
        If shtObj3.Cells(7, x + 4).Value = "Sim, 4 Bombas" Then
            revez4bombas area, clp, x, pg
        End If

        pgdc = CLng(shtObj3.Cells(13, x + 5).Value)
        b = 0
        b = CLng(shtObj3.Cells(7, x + 2).Value)
        z = 13
        For i = 1 To b
            If shtObj3.Cells(7, x + 4).Value = "Não" Then
                acionamento area, clp, x, z, pg, pgdc
            End If
            If shtObj3.Cells(7, x + 4).Value = "Sim, 2 Bombas" Then
                acionamento2bombas area, clp, x, z, pg, pgdc
            End If
            If shtObj3.Cells(7, x + 4).Value = "Sim, 3 Bombas" Then
                acionamento3bombas area, clp, x, z, pg, pgdc
            End If
            If shtObj3.Cells(7, x + 4).Value = "Sim, 4 Bombas" Then
                acionamento4bombas area, clp, x, z, i, pg, pgdc
            End If
            
            z = z + 6
        Next i
        
        b = 0
        b = CLng(shtObj3.Cells(7, x + 2).Value)
        z = 13
        For i = 1 To b
            If shtObj3.Cells(z + 2, x + 5).Value = "Sim" Then
                ethernet area, clp, x, z, pe
            End If
            
            z = z + 6
        Next i
        
        horastrabalhadas area, clp, x, z, pgdc
    
        x = x + 9
    Next y

    valv area, clp
    
    ultimalinha area, clp
    
    JUNK = CreateSelectionSets()
    JUNK = GetObjectSelectionSet(CStr("FOLHA_DIAGRAMA_R02"), objSelection10)
    JUNK = GetObjectSelectionSet(CStr("OUT_REF_DL"), objSelection11)
    JUNK = GetObjectSelectionSet(CStr("IN_REF_DL"), objSelection12)
    JUNK = GetObjectSelectionSet(CStr("OUT_REF_DC"), objSelection13)
    JUNK = GetObjectSelectionSet(CStr("IN_REF_DC"), objSelection14)
    
    For Each objBRef1 In objSelection12 '
        varAttribs1 = objBRef1.GetAttributes
        For Each objBRef2 In objSelection11
            varAttribs2 = objBRef2.GetAttributes
            If varAttribs1(2).TextString = "-" Then
                If varAttribs1(0).TextString = varAttribs2(0).TextString And varAttribs1(1).TextString = varAttribs2(1).TextString Then
                    varAttribs1(2).TextString = varAttribs2(2).TextString
                End If
            End If
        Next objBRef2
    Next objBRef1
    
    For Each objBRef1 In objSelection14 '
        varAttribs1 = objBRef1.GetAttributes
        For Each objBRef2 In objSelection13
            varAttribs2 = objBRef2.GetAttributes
            If varAttribs1(2).TextString = "-" Then
                If varAttribs1(0).TextString = varAttribs2(0).TextString And varAttribs1(1).TextString = varAttribs2(1).TextString Then
                    varAttribs1(2).TextString = varAttribs2(2).TextString
                End If
            End If
        Next objBRef2
    Next objBRef1
    
    For Each objBRef1 In objSelection10
        varAttribs1 = objBRef1.GetAttributes
        If varAttribs1(5).TextString = "DESCRIÇÃO " Then
            varInsertionPoint(0) = objBRef1.InsertionPoint(0)
            varInsertionPoint(1) = objBRef1.InsertionPoint(1)
            varInsertionPoint(2) = objBRef1.InsertionPoint(2)
            varAttribs1(5).TextString = "RESERVA"
            Set objBRef1 = ThisDrawing.ModelSpace.InsertBlock(varInsertionPoint, "RESERVA_R00", 1, 1, 1, 0)
        End If
    Next objBRef1
    JUNK = DeleteSelectionSets()
    UserForm1.show  
End Sub

Sub CommandButton5_Click()

    On Error Resume Next
    UserForm1.Hide
    Err.Clear
    Set excelApp = GetObject("D:\Teste.xlsx", "Excel.Application")
    If Err <> 0 Then
        Err.Clear
        'MsgBox "Nenhum Excel rodando", vbExclamation
    End If
    excelApp.DisplayAlerts = False
    excelApp.Quit
    End
    
End Sub
